### ISSUE TITLE
SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

### ISSUE THREAD

**Issue by SirLancelot-OG** [AugurProject/augur-node#682]
Have had some difficulties syncing my node. Is there a known fix for this? I'm thinking I may just need to run a clean start again?

```
Oct 16 21:36:56 augur nodejs-augur[30691]: new block: 6500136, 1539332224 (Fri Oct 12 2018 09:17:04 GMT+0100 (BST))
Oct 16 21:36:57 augur nodejs-augur[30691]: Processing 2 logs
Oct 16 21:36:57 augur nodejs-augur[30691]: update `balances` set `balance` = '-100000000000000' where `token` = '0xf92504468c7cb6c84f658e9ab82c31b7012b4216' and `owner` = '0x2a544ee7dca6663841ac2956530bbd1bd482e657' - SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance
Oct 16 21:36:57 augur nodejs-augur[30691]: Stopping Augur Node Server
```

**Comment by pgebheim** [comment]
Hello!

This functionally means the database is corrupted, because we have a balance recorded which would sink below zero by applying this log. There have been a few different reasons for the error, most notably when attempting to sync against an eth node which is still syncing (e.g. with Party Warp Sync), or Infura (or another pool of nodes).

This is because in these cases we sometimes get responses from the node that indicate that there are no logs for a particular block, when in fact that node just doesn't yet *have* the logs for that block. When that happens, we miss data coming off the eth node.

We're still looking into some places where we've seen this happen on single nodes as well -- so if you could provide any information about your configuration that would help!

**Comment by adrake33** [comment]
This is likely happening due to a bad re-org occurring. EIP-234 fixes this by adding `blockHash` as a filter that can be specified when calling `eth_newFilter`: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md.

EIP-234 has been implemented in geth and Parity and has been added to EthereumJS-blockstream: https://github.com/ethereumjs/ethereumjs-blockstream/pull/25. We are currently updating the Augur codebase to include this change to EthereumJS-blockstream in the next release of Augur.
